project_name = 'move-project'
home = '/Users/liangping/workspace/move-runner/sample'

[workspace]
script_dir = 'src/scripts'
module_dir = 'src/modules'
target_dir = 'target'
test_dir = 'test'


[compile]
output_source_map = true
output_move_bytecode = true
skip_stdlib = false
custom_stdlib = false
custom_stdlib_path = 'src/stdlib'

[tx]
address = '3cf4cc0c7dcf04ff846484288a4f40ef'
#address = 'cf1fe4b268ee11f5eb2cfbd7279cd789'
keypair_private_key = '47e2c2872d019e88326ca83be97d960727122b160cb51723abac0ab4ffd38a07'
keypair_public_key = 'c2d797e4752579f291903a57db187a56245badb13286f2944244bc178e37a5ca'
sequence_number = 0

[storage]
load_state_from_genesis = false
save_writeset_to_genesis = false
